dgs:
  graphql:
    graphiql:
      enabled: false

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    table: schema_history
    enabled: false

server:
  port: 7887

profiles:
  active: dev
