name: Build Node Controller
  
on: 
  push:
    paths:
      - "door-access-node-controller/**"
  pull_request:
    paths:
      - "door-access-node-controller/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./door-access-node-controller
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib install
    - name: Run PlatformIO
      run: pio run -e uno
